// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzcxybljzhwwwshykbtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Y3h5Ymxqemh3d3dzaHlrYnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTgwNzUsImV4cCI6MjA2NjQ5NDA3NX0.9IWDpEGtF5NM3mkfAkYdF8p17g-mlC3VYYT8Fm13Qi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);